package com.app.oneklikai.util;

import ai.djl.MalformedModelException;
import ai.djl.Model;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;

public class MemoryModelSerializer {

    public static byte[] serializeToBytes(Model model) throws IOException {
        Path tempDir = Files.createTempDirectory("djl_model_");
        try {
            // DJL saves parameter files into the temporary directory
            model.save(tempDir, model.getName());

            // Locate the generated model parameters file. Order matters: DJL may also emit metadata
            // files next to the weights, and Files.list() gives no ordering guarantee.
            try (var stream = Files.list(tempDir)) {
                List<Path> files = stream.toList();
                Path paramFile = firstMatching(files, ".params")
                        .or(() -> firstMatching(files, ".pt"))
                        .orElseThrow(() -> new IOException("No parameter file generated by DJL model save."));

                return Files.readAllBytes(paramFile);
            }
        } finally {
            // Clean up temporary directory and files immediately
            deleteDirectoryRecursive(tempDir);
        }
    }


    public static void deserializeFromBytes(Model model, byte[] weightBytes, String modelName)
            throws IOException, MalformedModelException {
        Path tempDir = Files.createTempDirectory("djl_load_");
        try {
            // Write byte array to temporary parameter file
            Path paramFile = tempDir.resolve(modelName + "-0000.params");
            Files.write(paramFile, weightBytes);

            // Load model weights from temporary path
            model.load(tempDir, modelName);
        } finally {
            // Clean up temporary directory and files immediately
            deleteDirectoryRecursive(tempDir);
        }
    }

    private static Optional<Path> firstMatching(List<Path> files, String suffix) {
        return files.stream().filter(p -> p.toString().endsWith(suffix)).findFirst();
    }

    private static void deleteDirectoryRecursive(Path dir) throws IOException {
        if (Files.exists(dir)) {
            try (var stream = Files.walk(dir)) {
                stream.sorted(Comparator.reverseOrder())
                        .forEach(p -> {
                            try {
                                Files.delete(p);
                            } catch (IOException ignored) {
                            }
                        });
            }
        }
    }
}