package com.app.oneklikai.util;

import ai.djl.MalformedModelException;
import ai.djl.Model;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;

public class MemoryModelSerializer {

    public static byte[] serializeToBytes(Model model) throws IOException {
        Path tempDir = Files.createTempDirectory("djl_model_");
        try {
            // DJL saves parameter files into the temporary directory
            model.save(tempDir, model.getName());

            // Locate the generated model parameters file (.params or .pt)
            try (var stream = Files.list(tempDir)) {
                Path paramFile = stream
                        .filter(p -> p.toString().endsWith(".params") || p.toString().endsWith(".pt") || p.toString().endsWith(".json"))
                        .findFirst()
                        .orElseThrow(() -> new IOException("No parameter file generated by DJL model save."));

                return Files.readAllBytes(paramFile);
            }
        } finally {
            // Clean up temporary directory and files immediately
            deleteDirectoryRecursive(tempDir);
        }
    }


    public static void deserializeFromBytes(Model model, byte[] weightBytes, String modelName)
            throws IOException, MalformedModelException {
        Path tempDir = Files.createTempDirectory("djl_load_");
        try {
            // Write byte array to temporary parameter file
            Path paramFile = tempDir.resolve(modelName + "-0000.params");
            Files.write(paramFile, weightBytes);

            // Load model weights from temporary path
            model.load(tempDir, modelName);
        } finally {
            // Clean up temporary directory and files immediately
            deleteDirectoryRecursive(tempDir);
        }
    }

    private static void deleteDirectoryRecursive(Path dir) throws IOException {
        if (Files.exists(dir)) {
            try (var stream = Files.walk(dir)) {
                stream.sorted(Comparator.reverseOrder())
                        .forEach(p -> {
                            try {
                                Files.delete(p);
                            } catch (IOException ignored) {
                            }
                        });
            }
        }
    }
}